
package fr.giwi.agreuhgatorservice.rssentrymanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Apr 07 21:33:35 CEST 2010
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "ClientProtocolException", targetNamespace = "http://giwi.fr/AgreuhGatorservice/RssEntryManager")
public class ClientProtocolException_Exception extends Exception {
    public static final long serialVersionUID = 20100403135223L;
    
    private fr.giwi.agreuhgatorservice.rssentrymanager.ClientProtocolException clientProtocolException;

    public ClientProtocolException_Exception() {
        super();
    }
    
    public ClientProtocolException_Exception(String message) {
        super(message);
    }
    
    public ClientProtocolException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ClientProtocolException_Exception(String message, fr.giwi.agreuhgatorservice.rssentrymanager.ClientProtocolException clientProtocolException) {
        super(message);
        this.clientProtocolException = clientProtocolException;
    }

    public ClientProtocolException_Exception(String message, fr.giwi.agreuhgatorservice.rssentrymanager.ClientProtocolException clientProtocolException, Throwable cause) {
        super(message, cause);
        this.clientProtocolException = clientProtocolException;
    }

    public fr.giwi.agreuhgatorservice.rssentrymanager.ClientProtocolException getFaultInfo() {
        return this.clientProtocolException;
    }
}
