
package fr.giwi.agreuhgatorservice.rssentrymanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Apr 07 21:33:35 CEST 2010
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "IOException", targetNamespace = "http://giwi.fr/AgreuhGatorservice/RssEntryManager")
public class IOException_Exception extends Exception {
    public static final long serialVersionUID = 20100403135223L;
    
    private fr.giwi.agreuhgatorservice.rssentrymanager.IOException ioException;

    public IOException_Exception() {
        super();
    }
    
    public IOException_Exception(String message) {
        super(message);
    }
    
    public IOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IOException_Exception(String message, fr.giwi.agreuhgatorservice.rssentrymanager.IOException ioException) {
        super(message);
        this.ioException = ioException;
    }

    public IOException_Exception(String message, fr.giwi.agreuhgatorservice.rssentrymanager.IOException ioException, Throwable cause) {
        super(message, cause);
        this.ioException = ioException;
    }

    public fr.giwi.agreuhgatorservice.rssentrymanager.IOException getFaultInfo() {
        return this.ioException;
    }
}
