
/*
 * 
 */

package fr.giwi.agreuhgatorservice.rssentrymanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Apr 07 21:33:35 CEST 2010
 * Generated source version: 2.2.5
 * 
 */


@WebServiceClient(name = "RssEntryManager", 
                  wsdlLocation = "http://flufy.hd.free.fr:8080/AgreuhGatorService/services/RssEntryManager?wsdl",
                  targetNamespace = "http://giwi.fr/AgreuhGatorservice/RssEntryManager") 
public class RssEntryManager extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://giwi.fr/AgreuhGatorservice/RssEntryManager", "RssEntryManager");
    public final static QName RssEntryManagerPort = new QName("http://giwi.fr/AgreuhGatorservice/RssEntryManager", "RssEntryManagerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://flufy.hd.free.fr:8080/AgreuhGatorService/services/RssEntryManager?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://flufy.hd.free.fr:8080/AgreuhGatorService/services/RssEntryManager?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public RssEntryManager(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RssEntryManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RssEntryManager() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns RssEntryManageable
     */
    @WebEndpoint(name = "RssEntryManagerPort")
    public RssEntryManageable getRssEntryManagerPort() {
        return super.getPort(RssEntryManagerPort, RssEntryManageable.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RssEntryManageable
     */
    @WebEndpoint(name = "RssEntryManagerPort")
    public RssEntryManageable getRssEntryManagerPort(WebServiceFeature... features) {
        return super.getPort(RssEntryManagerPort, RssEntryManageable.class, features);
    }

}
