
package fr.giwi.agreuhgatorservice.rssentrymanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Apr 07 21:33:35 CEST 2010
 * Generated source version: 2.2.5
 * 
 */

@WebFault(name = "FeedException", targetNamespace = "http://giwi.fr/AgreuhGatorservice/RssEntryManager")
public class FeedException_Exception extends Exception {
    public static final long serialVersionUID = 20100403135223L;
    
    private fr.giwi.agreuhgatorservice.rssentrymanager.FeedException feedException;

    public FeedException_Exception() {
        super();
    }
    
    public FeedException_Exception(String message) {
        super(message);
    }
    
    public FeedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public FeedException_Exception(String message, fr.giwi.agreuhgatorservice.rssentrymanager.FeedException feedException) {
        super(message);
        this.feedException = feedException;
    }

    public FeedException_Exception(String message, fr.giwi.agreuhgatorservice.rssentrymanager.FeedException feedException, Throwable cause) {
        super(message, cause);
        this.feedException = feedException;
    }

    public fr.giwi.agreuhgatorservice.rssentrymanager.FeedException getFaultInfo() {
        return this.feedException;
    }
}
