
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.giwi.agreuhgatorservice.rssentrymanager;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Apr 07 21:33:35 CEST 2010
 * Generated source version: 2.2.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "RssEntryManager",
                      portName = "RssEntryManagerPort",
                      targetNamespace = "http://giwi.fr/AgreuhGatorservice/RssEntryManager",
                      wsdlLocation = "http://flufy.hd.free.fr:8080/AgreuhGatorService/services/RssEntryManager?wsdl",
                      endpointInterface = "fr.giwi.agreuhgatorservice.rssentrymanager.RssEntryManageable")
                      
public class RssEntryManageableImpl implements RssEntryManageable {

    private static final Logger LOG = Logger.getLogger(RssEntryManageableImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.giwi.agreuhgatorservice.rssentrymanager.RssEntryManageable#getEntry(int  id )*
     */
    public fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry getEntry(int id) { 
        LOG.info("Executing operation getEntry");
        System.out.println(id);
        try {
            fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.giwi.agreuhgatorservice.rssentrymanager.RssEntryManageable#updateRssEntry(fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry  rssEntry )*
     */
    public void updateRssEntry(fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry rssEntry) { 
        LOG.info("Executing operation updateRssEntry");
        System.out.println(rssEntry);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.giwi.agreuhgatorservice.rssentrymanager.RssEntryManageable#isValidFeed(java.lang.String  url )*
     */
    public boolean isValidFeed(java.lang.String url) throws IOException_Exception , ClientProtocolException_Exception    { 
        LOG.info("Executing operation isValidFeed");
        System.out.println(url);
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IOException_Exception("IOException...");
        //throw new ClientProtocolException_Exception("ClientProtocolException...");
    }

    /* (non-Javadoc)
     * @see fr.giwi.agreuhgatorservice.rssentrymanager.RssEntryManageable#deleteRssEntry(int  id )*
     */
    public void deleteRssEntry(int id) { 
        LOG.info("Executing operation deleteRssEntry");
        System.out.println(id);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.giwi.agreuhgatorservice.rssentrymanager.RssEntryManageable#isExistRssFeed(java.lang.String  url )*
     */
    public boolean isExistRssFeed(java.lang.String url) { 
        LOG.info("Executing operation isExistRssFeed");
        System.out.println(url);
        try {
            boolean _return = false;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.giwi.agreuhgatorservice.rssentrymanager.RssEntryManageable#addRssEntry(fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry  rssEntry )*
     */
    public void addRssEntry(fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry rssEntry) throws IllegalArgumentException_Exception , IOException_Exception , FeedException_Exception    { 
        LOG.info("Executing operation addRssEntry");
        System.out.println(rssEntry);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IllegalArgumentException_Exception("IllegalArgumentException...");
        //throw new IOException_Exception("IOException...");
        //throw new FeedException_Exception("FeedException...");
    }

    /* (non-Javadoc)
     * @see fr.giwi.agreuhgatorservice.rssentrymanager.RssEntryManageable#getRssEntries(*
     */
    public java.util.List<fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry> getRssEntries() { 
        LOG.info("Executing operation getRssEntries");
        try {
            java.util.List<fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry> _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
