
package fr.giwi.agreuhgatorservice.rssentrymanager;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.5
 * Wed Apr 07 21:33:35 CEST 2010
 * Generated source version: 2.2.5
 * 
 */

public final class RssEntryManageable_RssEntryManagerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://giwi.fr/AgreuhGatorservice/RssEntryManager", "RssEntryManager");

    private RssEntryManageable_RssEntryManagerPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = RssEntryManager.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RssEntryManager ss = new RssEntryManager(wsdlURL, SERVICE_NAME);
        RssEntryManageable port = ss.getRssEntryManagerPort();  
        
        {
        System.out.println("Invoking getEntry...");
        int _getEntry_id = 0;
        fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry _getEntry__return = port.getEntry(_getEntry_id);
        System.out.println("getEntry.result=" + _getEntry__return);


        }
        {
        System.out.println("Invoking updateRssEntry...");
        fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry _updateRssEntry_rssEntry = null;
        port.updateRssEntry(_updateRssEntry_rssEntry);


        }
        {
        System.out.println("Invoking isValidFeed...");
        java.lang.String _isValidFeed_url = "";
        try {
            boolean _isValidFeed__return = port.isValidFeed(_isValidFeed_url);
            System.out.println("isValidFeed.result=" + _isValidFeed__return);

        } catch (IOException_Exception e) { 
            System.out.println("Expected exception: IOException has occurred.");
            System.out.println(e.toString());
        } catch (ClientProtocolException_Exception e) { 
            System.out.println("Expected exception: ClientProtocolException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteRssEntry...");
        int _deleteRssEntry_id = 0;
        port.deleteRssEntry(_deleteRssEntry_id);


        }
        {
        System.out.println("Invoking isExistRssFeed...");
        java.lang.String _isExistRssFeed_url = "";
        boolean _isExistRssFeed__return = port.isExistRssFeed(_isExistRssFeed_url);
        System.out.println("isExistRssFeed.result=" + _isExistRssFeed__return);


        }
        {
        System.out.println("Invoking addRssEntry...");
        fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry _addRssEntry_rssEntry = null;
        try {
            port.addRssEntry(_addRssEntry_rssEntry);

        } catch (IllegalArgumentException_Exception e) { 
            System.out.println("Expected exception: IllegalArgumentException has occurred.");
            System.out.println(e.toString());
        } catch (IOException_Exception e) { 
            System.out.println("Expected exception: IOException has occurred.");
            System.out.println(e.toString());
        } catch (FeedException_Exception e) { 
            System.out.println("Expected exception: FeedException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRssEntries...");
        java.util.List<fr.giwi.agreuhgatorservice.rssentrymanager.RssEntry> _getRssEntries__return = port.getRssEntries();
        System.out.println("getRssEntries.result=" + _getRssEntries__return);


        }

        System.exit(0);
    }

}
